package com.meituan.olee.parser;

public enum StateType {
    expectOperand,
    expectBinOp,
    arrayVal,
    expectObjKey,
    objKey,
    expectKeyValSep,
    objVal,
    spread,
    objSpreadVal,
    computedMember,
    member,
    def,
    defAssign,
    defVal,
    fn,
    fnArg,
    fnPostArg,
    fnArrow,
    fnExpr,
    expectTransform,
    postTransform,
    exprTransform,
    subExp,
    argVal,
    ternaryMid,
    ternaryEnd,
    complete,
}
